default:
  skip_cleanup: false
  ssl_verify: true
  http2: false
  threescale:
    service:
      backends:
        primary: https://echo-api.3scale.net:443
        httpbin: https://httpbin.org:443
        echo_api: https://echo-api.3scale.net:443
        httpbin_nossl: http://httpbin.org:80
    gateway:
      TemplateApicast:
        template: apicast.yml
      OperatorApicast:
        openshift:
          project_name: "apicast-ga"
          kind: "OpenShiftClient"
      WASMGateway:
        image: "registry.redhat.io/openshift-service-mesh/3scale-auth-wasm-rhel8:0.0.1"
      default:
        kind: "SystemApicast"
  rhsso:
    username: admin
    test_user:
      username: testUser
      password: testUser
  redis:
    url: redis://apicast-testing-redis:6379/1
  proxy:
    http: "@format http://tinyproxy-service.{this.FIXTURES.tools.namespace}.svc:8888"
    https: "@format http://tinyproxy-service.{this.FIXTURES.tools.namespace}.svc:8888"
  toolbox:
    cmd: "podman"
    podman_cert_dir: "/var/data"
    podman_cert_name: "ca-bundle.crt"
  integration:
    service:
      proxy_service: "@format fuse-camel-proxy.{this.FIXTURES.tools.namespace}.svc:8088"
  fixtures:
    tools:
      namespace: tools
    custom_httpbin:
      image: quay.io/jsmadis/go-httpbin:latest
    lifecycle_hooks:
      defaults: [staging_gateway, production_gateway]
    jaeger:
      config:
        reporter:
          localAgentHostPort: "@format jaeger-agent.{this.FIXTURES.tools.namespace}.svc:6831"
        baggage_restrictions:
          hostPort: "@format jaeger-query.{this.FIXTURES.tools.namespace}.svc:5778"
    ui:
      browser:
        source: local
        webdriver: chrome
        remote_url: http://127.0.0.1:4444
        binary_path: ""


  hyperfoil:
    shared_template:
      # We need to add agents definition for clustered hyperfoil to each test
      agents:
        agent-one:
  cfssl:
    binary: "cfssl"
